# Generated by Django 6.0.1 on 2026-01-24 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cetagory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cetagory_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=50, null=True)),
                ("last_name", models.CharField(blank=True, max_length=50, null=True)),
                ("email", models.EmailField(max_length=100, unique=True)),
                ("password", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=15)),
                ("reg_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(blank=True, max_length=50, null=True)),
                ("item_price", models.DecimalField(decimal_places=1, max_digits=10)),
                (
                    "item_description",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
                ("image", models.ImageField(upload_to="food_image/")),
                ("item_quantity", models.CharField(max_length=100)),
                ("is_available", models.BooleanField(default=True)),
                (
                    "cetagory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="food_ordering.cetagory",
                    ),
                ),
            ],
        ),
    ]
