# Generated by Django 6.0.1 on 2026-01-28 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("food_ordering", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Cetagory",
            new_name="Category",
        ),
        migrations.RenameField(
            model_name="category",
            old_name="cetagory_name",
            new_name="category_name",
        ),
    ]
