# Generated by Django 6.0.1 on 2026-01-29 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("food_ordering", "0002_rename_cetagory_category_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="food",
            old_name="cetagory",
            new_name="category",
        ),
    ]
