# Generated by Django 6.0.1 on 2026-01-30 10:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_ordering", "0003_rename_cetagory_food_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="creation_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
