# Generated by Django 6.0.1 on 2026-01-30 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_ordering", "0004_food_creation_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="food_image/"),
        ),
    ]
