# Generated by Django 6.0.1 on 2026-02-14 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_ordering", "0006_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_order_placed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
