# Generated by Django 6.0.1 on 2026-02-14 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("food_ordering", "0008_alter_order_options_order_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="order",
            unique_together=set(),
        ),
    ]
