# Generated by Django 6.0.1 on 2026-02-17 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_ordering", "0009_alter_order_options_alter_order_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("remark", models.CharField(max_length=200, null=True)),
                ("status", models.CharField(max_length=200, null=True)),
                ("status_date", models.DateTimeField(auto_now_add=True)),
                ("order_cancelled_by_user", models.BooleanField(null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="food_ordering.order",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_number", models.CharField(max_length=100, null=True)),
                ("address", models.TextField()),
                ("order_time", models.DateTimeField(auto_now_add=True)),
                ("order_final_status", models.CharField(max_length=200, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="food_ordering.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_number", models.CharField(max_length=100, null=True)),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[
                            ("cod", "Cash on Delivery"),
                            ("online", "Online payment "),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("card_number", models.CharField(blank=True, max_length=20, null=True)),
                ("expiry_date", models.CharField(blank=True, max_length=10, null=True)),
                ("cvv", models.CharField(blank=True, max_length=5, null=True)),
                ("payment_date", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="food_ordering.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.PositiveBigIntegerField(default=1)),
                ("comment", models.TextField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="food_ordering.food",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="food_ordering.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_on", models.DateTimeField(auto_now_add=True)),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="food_ordering.food",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="food_ordering.user",
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "food")},
            },
        ),
    ]
